"""voxd package -- audio server daemon."""
# pyright: reportPrivateUsage=false
# Re-exporting private names from submodules is the whole point of __init__.py.

from __future__ import annotations

from punt_vox.voxd._monolith import (
    _HANDLERS,
    _MAX_STDERR_LEN,
    _PLAYBACK_TIMEOUT_DEFAULT_S,
    DEFAULT_HOST,
    DEFAULT_PORT,
    DaemonContext,
    PlaybackItem,
    _apply_vibe_for_synthesis,
    _auto_track_name,
    _handle_music_list,
    _handle_music_next,
    _handle_music_off,
    _handle_music_on,
    _handle_music_play,
    _handle_music_vibe,
    _handle_synthesize,
    _health_payload_full,
    _health_payload_minimal,
    _health_route,
    _kill_music_proc,
    _load_keys,
    _model_supports_expressive_tags,
    _monotonic,
    _music_loop,
    _music_player_command,
    _play_audio,
    _probe_duration,
    _synthesize_to_file,
    _truncate_stderr,
    _try_direct_play,
    _ws_route,
    build_app,
    cli,
    entrypoint,
    main,
    read_port_file,
    read_token_file,
)
from punt_vox.voxd.chimes import ChimeResolver
from punt_vox.voxd.config import (
    DaemonConfig,
    _config_dir,
    _install_token_redact_filter,
    _log_dir,
    _run_dir,
)
from punt_vox.voxd.dedup import (
    _DEDUP_WINDOW_SECONDS,
    _ONCE_DEDUP_MAX_ENTRIES,
    _ONCE_DEDUP_MAX_TTL_SECONDS,
    ChimeDedup,
    DedupHit,
    OnceDedup,
)

__all__ = [
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "_DEDUP_WINDOW_SECONDS",
    "_HANDLERS",
    "_MAX_STDERR_LEN",
    "_ONCE_DEDUP_MAX_ENTRIES",
    "_ONCE_DEDUP_MAX_TTL_SECONDS",
    "_PLAYBACK_TIMEOUT_DEFAULT_S",
    "ChimeDedup",
    "ChimeResolver",
    "DaemonConfig",
    "DaemonContext",
    "DedupHit",
    "OnceDedup",
    "PlaybackItem",
    "_apply_vibe_for_synthesis",
    "_auto_track_name",
    "_config_dir",
    "_handle_music_list",
    "_handle_music_next",
    "_handle_music_off",
    "_handle_music_on",
    "_handle_music_play",
    "_handle_music_vibe",
    "_handle_synthesize",
    "_health_payload_full",
    "_health_payload_minimal",
    "_health_route",
    "_install_token_redact_filter",
    "_kill_music_proc",
    "_load_keys",
    "_log_dir",
    "_model_supports_expressive_tags",
    "_monotonic",
    "_music_loop",
    "_music_player_command",
    "_play_audio",
    "_probe_duration",
    "_run_dir",
    "_synthesize_to_file",
    "_truncate_stderr",
    "_try_direct_play",
    "_ws_route",
    "build_app",
    "cli",
    "entrypoint",
    "main",
    "read_port_file",
    "read_token_file",
]
