from io import BytesIO
from pathlib import Path

class AudioSegment:
    @classmethod
    def from_mp3(cls, file: str | Path) -> AudioSegment: ...
    @classmethod
    def from_file(cls, file: str | Path, format: str | None = None) -> AudioSegment: ...
    @classmethod
    def silent(cls, duration: int = 0) -> AudioSegment: ...
    def export(self, out_f: str | Path | BytesIO, format: str = "mp3") -> object: ...
    def __add__(self, other: AudioSegment) -> AudioSegment: ...
    def __len__(self) -> int: ...
    @property
    def duration_seconds(self) -> float: ...
