from pathlib import Path
from typing import IO

class Frame: ...

class TextFrame(Frame):
    text: list[str]
    def __init__(self, *, encoding: int = ..., text: list[str] = ...) -> None: ...

class TIT2(TextFrame): ...
class TALB(TextFrame): ...
class TPE1(TextFrame): ...
class TPE2(TextFrame): ...
class TCON(TextFrame): ...
class TRCK(TextFrame): ...

class ID3:
    def __init__(self, filething: str | Path | IO[bytes] | None = ...) -> None: ...
    def add(self, frame: Frame) -> None: ...
    def save(self, filething: str | Path | IO[bytes] | None = ...) -> None: ...
    def __getitem__(self, key: str) -> TextFrame: ...
